ublue-os/fleek

core/flake.go, core/flake.nix.tmpl, core/user.nix.tmpl
This change adds per-host user configs for adding additional configuration at the host level.
=> feat: per host user configs

core/flake.go
dont overwrite host/user.nix on flake apply
=> fix: don't overwrite host user

core/shell.nix.tmpl
add exa aliases for HIGH bling.
=> feat: exa aliases

cmd/init.go
=> fix: fix println with printf variables

cmd/update.go, core/flake.go, locales/en.yml, main.go
add `fleek update` command, with flag to immediately apply.
=> feat: fleek update

Containerfile, push.sh
build in container instead of locally
=> fix: build in container

cmd/init.go, cmd/root.go
=> fix: don't commit on init -a-c

nix/shell.nix.tmpl
=> fix: only source local nix profile if it exists

nix/aliases.nix.tmpl, nix/shell.nix.tmpl
add some nice aliases for high BLING levels
=> feat: new high bling aliases

.gitignore, Containerfile, Justfile
adds `just man` to generate all possible manpages from list of locales/ directory
=> feat: generate man pages in justfile

Justfile
=> fix: source .env file

internal/nix/shell.nix.tmpl
sources fleek completions in generated rc scripts
=> feat: add completions

.goreleaser.yaml
tag only official releases with :latest
nightly releases get :dev
=> feat: docker tags more good

.goreleaser.yaml
=> fix: moar tags

internal/flake/flake.go, internal/flake/git.go, internal/fleekcli/init.go, locales/en.yml
`fleek init git@github.com:your/repo` now works!
=> feat: init git repo

completions/fleek.bash, completions/fleek.fish, completions/fleek.zsh, fin/fin.go, internal/fleekcli/man.go
remove extra formatting on stdout
=> fix: completions with terminal codes

flake.nix
adds a version to the flake built app
=> fix: version

Justfile, README.md, flake.nix, scripts/create-release.sh
=> fix: link in readme

internal/flake/flake.go, internal/fleek/config.go
use the force boolean supplied in params.
also, delete the symlink if it exists before trying to create it.
=> fix: use force from parameters

internal/fleekcli/root.go
=> fix: deprecation check on mac

locales/es.yml
I tried to stick as faithfully as possible to the original phrasing and meaning, with minimal changes to accommodate better the translation of some ideas in Spanish.
=> feat: Add Spanish translation

internal/flake/templates/aliases.nix.tmpl, internal/flake/templates/flake.nix.tmpl, internal/flake/templates/home.nix.tmpl, internal/flake/templates/host.nix.tmpl, internal/flake/templates/path.nix.tmpl, internal/flake/templates/programs.nix.tmpl, internal/flake/templates/shell.nix.tmpl, internal/flake/templates/user.nix.tmpl
add comments to managed nix files, warning that they will be overwritten.
fixes #140
=> docs: add comments to templates

internal/fleekcli/init.go, internal/fleekcli/root.go
Move location flag out of init command to be a persistent flag of the root command
=> fix: respect location flag

.github/workflows/flakehub-publish-tagged.yml
=> feat: Create flakehub-publish-tagged.yml

internal/flake/git.go, internal/fleek/config.go
Add `update-fleek` and `latest-fleek-version` as aliases to all configs.
=> feat: fleek-provided aliases for updating and version checks

internal/flake/templates/aliases.nix.tmpl, internal/fleek/config.go
use the new allAliases function in the flake template
=> fix: use allAliases function

internal/fleek/config.go, internal/fleek/config_test.go
This PR adds tests, but no new functionality.
=> chore: add config tests

internal/cache/cache.go
=> fix nix search all packages command
