ublue-os/fleek

cmd/fleek.go, cmd/root.go, core/system.go
if .fleek.yml contains a shell: line that doesn't match the user's login shell, display a warning at the end of a fleek command run.
=> feat: display warning about mismatch in configured vs login shells

internal/core/programs.yml, internal/fleekcli/info.go, internal/fleekcli/root.go, locales/en.yml
=> feat: info command

locales/en.yml
add docs pointing to https://getfleek.dev/docs/multiple for multiple computer configs
=> docs: add docs about sharing configs

.goreleaser.yaml
This change adds a homebrew tap for fleek in ublue-os/homebrew-tap.
It might even work...
=> feat: homebrew tap

internal/flake/flake.go
fixes #141 - adds -no-write-lock-file to flake run
=> fix: flake lock error with home-manager

README.md
The link goes to my old archived repo and it will no longer be updated. Now the link goes to my new repo. I created a repo and migrated all of my nix stuff to one repo so it is easier to manage.
=> docs: script link goes to my script in new repo

internal/fleek/config.go
don't prompt to choose a key when there are no candidates.
fixes #174
=> fix: error when no ssh keys in existing ssh directory

internal/flake/templates/README.md.tmpl
Fixed formatting of aliases flowing into the previous line and switched the links to a list.
=> docs: fix README template formatting

internal/flake/templates/flake.nix.tmpl, internal/fleek/config.go
This allows users to add an `overlays` section in the .fleek.yml, which is then fed into the homeConfigurations for use in packages and user.nix. The motivating use case was being able to use the emacs overlay, which grants access to both more recent versions of emacs as well as the contents of ELPA and MELPA.
To add overlays, you add something like the following to `.fleek.yml`:
```yaml
overlays:
emacs:
url: github:nix-community/emacs-overlay
follow: true
nur:
url: github:nix-community/NUR
follow: false
```
Once that's there, you can reference the overlays in `user.nix` -- for example, to grab the GTK build of emacs and a theme, you'd add the following to `user.nix`:
```nix
programs.emacs = {
package = pkgs.emacsPgtk;
extraPackages = epkgs:
with epkgs; [
base16-theme
];
};
```
=> Add support for defining overlays in YAML

internal/fleek/config.go
this fixes #221 for me -- not really familiar with go or any of its tooling, apologies if formatting is off
=> fix double prepend $HOME when reading .fleek.yml

internal/fleek/config.go
if the `systems` block specifies a `home` key, it will be used as the HOME location for a user.
=> feat: specify home in system config

internal/fleekcli/root.go
Not having this means users see a blank output on most commands with no way to identify why.
I mangled my nix installation, being new to nix. `nix list profiles` was returning an error due to a file being empty.
Fleek stopped responding to commands and I traced it to this. Instead of exiting, we should warn in some want to check on the nix installation. 
I'm not sure what the best message would be and defer to a nix knower.
=> Help when nix list responds in error

internal/flake/templates/shell.nix.tmpl
adds .nix-profile to XCURSOR_PATH to make things look good in QT/KDE environments.
=> fix: add XCURSOR_PATH

internal/fleek/config.go, internal/fleek/programs.yml
replaces 'exa' with 'eza'. Still may require manual update of programs.nix.
=> fix: replace exa with eza

internal/fleek/config.go
checks `FLEEK_USER_EMAIL`, `FLEEK_USER_NAME`, `FLEEK_USER_PUBKEY`, `FLEEK_USER_PRIVKEY` and uses them for current user's info on `fleek init`, making the init process non-interactive if at least NAME and EMAIL are set.
=> feat: use environment variables for init if they exist

README.md, internal/flake/flake.go, internal/flake/templates/flake.nix.tmpl, internal/fleek/config.go, internal/fleekcli/root.go, internal/fleekcli/update.go, internal/fleekcli/version.go, internal/fleekcli/write.go, locales/en.yml
* use flakehub to install fleek & home manager
* self-manage fleek (again)
* add `auto_gc` flag in fleek.yaml to run nix garbage collection on every run
=> feat: use flakehub for installs, self-manage fleek, autogc

internal/flake/templates/flake.nix.tmpl, internal/fleek/config.go
fixes a bug where the fleek binary would be added to the flake output multiple times if you had more than one system in your config with the same arch/os combo.
=> fix: unique arch-os combo in flake.nix

internal/fleek/system.go
Fleek will now use the value of `FLEEK_HOST_OVERRIDE` as the hostname when calculating which flake to apply to the current system.
This allows you to have a single shared definitions for ephemeral machines that all share the same attributes (OS/architecture), for example in automated development environments.
Set `FLEEK_HOST_OVERRIDE` to the name of the system definition you wish to declare/use before running Fleek.
```
export FLEEK_HOST_OVERRIDE=ubuntuvm
fleek join git@github.com:YOU/fleek
```
=> feat: Enable shared system definitons with host name override

internal/fleek/default.yml, internal/fleek/high.yml, internal/fleek/packages.yml
Add `just` to the default and high levels of bling.
=> feat: add just to default and high bling level

internal/fleek/config.go
unclutters output when auto garbage collection is on.
=> chore: remove verbose output from garbage collection

internal/fleekcli/add.go, internal/fleekcli/join.go, internal/fleekcli/remove.go, internal/fleekcli/update.go
Removes the annoying `apply` step from `fleek {add | join | remove | update}`.
Leaves the `apply` step in `fleek init` for now.
=> feat: remove apply flag from add,join,remove,update

internal/flake/flake.go, internal/flake/templates/flake.nix.tmpl, internal/fleek/config.go, internal/fleekcli/join.go
This change moves users out of the stand-alone array in .fleek.yaml and into a field under the system object. This prevents errors when the same username exists on different systems, but that system needs different user configs.
=> feat: migrate users to system

.goreleaser.yaml
apparently brew taps are deprecated. we don't recommend them anyway. Removing to fix the build.
=> chore: remove homebrew builds

internal/flake/flake.go
fix bad parens location on logger
=> fix: bad parens on logger
